spring:
  sensitive:
    security:
      type: AES    # 加密方式,默认AES
      mode: HEX    # 加密后得字节数组转换为字符串方式：HEX 16 进制, BASE64 base64
      secret: +6cuvzvyrFZpRG9pf3r7eQ== # 加密密钥 密钥请自行生成
      charset: UTF-8
      maxDeep: 10 # 处理脱敏，加解密对象的最大深度，防止相互依赖导致递归内存溢出，默认10